// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEye9tS3VG9ERLlFtDTJM2OCJcwS2ptU',
    appId: '1:1060241869601:web:e96de20f7fdc4eaaf00c60',
    messagingSenderId: '1060241869601',
    projectId: 'mycafe-dbd39',
    authDomain: 'mycafe-dbd39.firebaseapp.com',
    storageBucket: 'mycafe-dbd39.appspot.com',
    measurementId: 'G-3PXPD94027',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqaLktWUSe1M8rp5-EYajwfYyuhHvLM18',
    appId: '1:1060241869601:android:eb03da689c83defdf00c60',
    messagingSenderId: '1060241869601',
    projectId: 'mycafe-dbd39',
    storageBucket: 'mycafe-dbd39.appspot.com',
  );
}
